apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hello.service.name }}
spec:
  type: {{ .Values.hello.service.type }}
  selector:
    app: {{ .Values.hello.name }}
    tier: backend
  ports:
  - protocol: TCP
    port: {{ .Values.hello.service.port }}
    targetPort: {{ .Values.hello.service.targetPort }}