apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
    tier: frontend
  ports:
  - protocol: "TCP"
    port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.targetPort }}
  type: {{ .Values.nginx.service.type }}
